In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Flatten
from sklearn.metrics import accuracy_score

In [2]:
mnist = keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train.shape, y_train.shape, X_test.shape, y_test.shape

11501568/11490434 [==============================] - 0s 0us/step


((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [3]:
X_train, X_test = X_train/255.0, X_test/255.0

In [4]:
len(X_train[0])

28

In [5]:
model = Sequential()
model.add(Flatten(input_shape=(X_train.shape[1:])))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [7]:
loss = tf.losses.SparseCategoricalCrossentropy()
optimizer = tf.optimizers.Adam(learning_rate=0.001)
metrics = ['accuracy']

In [8]:
model.compile(loss=loss, optimizer=optimizer, metrics=metrics)

In [9]:
batch_size = 64
epochs = 10

In [10]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)          # 60000/64 = 937.5

Epoch 1/10
938/938 - 4s - loss: 0.2971 - accuracy: 0.9168
Epoch 2/10
938/938 - 2s - loss: 0.1345 - accuracy: 0.9611
Epoch 3/10
938/938 - 2s - loss: 0.0926 - accuracy: 0.9726
Epoch 4/10
938/938 - 2s - loss: 0.0702 - accuracy: 0.9791
Epoch 5/10
938/938 - 2s - loss: 0.0545 - accuracy: 0.9840
Epoch 6/10
938/938 - 2s - loss: 0.0428 - accuracy: 0.9876
Epoch 7/10
938/938 - 2s - loss: 0.0359 - accuracy: 0.9895
Epoch 8/10
938/938 - 2s - loss: 0.0284 - accuracy: 0.9919
Epoch 9/10
938/938 - 2s - loss: 0.0238 - accuracy: 0.9931
Epoch 10/10
938/938 - 2s - loss: 0.0194 - accuracy: 0.9948


In [11]:
model.evaluate(X_test, y_test, batch_size=batch_size, verbose=2)                      # 10000/64 = 156.25

157/157 - 0s - loss: 0.0743 - accuracy: 0.9790


[0.07428387552499771, 0.9789999723434448]

In [12]:
y_pred = model.predict(X_test)
y_pred[:5]

array([[6.7470310e-08, 1.9374660e-10, 1.8405760e-07, 2.1929980e-05,
        9.1763732e-12, 5.4184022e-09, 1.5959037e-13, 9.9996328e-01,
        5.9938969e-07, 1.3897611e-05],
       [4.1179757e-09, 4.8158372e-06, 9.9998581e-01, 6.9197256e-07,
        4.8637537e-16, 8.2436054e-06, 2.2981546e-08, 8.6479272e-14,
        4.3187347e-07, 2.4457435e-15],
       [3.6448159e-07, 9.9817085e-01, 3.0747731e-04, 4.9165196e-06,
        6.4768254e-05, 1.6696034e-05, 1.1045418e-05, 6.4079737e-04,
        7.8226038e-04, 8.2376221e-07],
       [9.9999440e-01, 1.1172242e-12, 4.1431258e-06, 4.7518136e-09,
        1.5116037e-09, 6.6587043e-09, 1.5311193e-07, 4.4723894e-08,
        3.1196801e-10, 1.2135558e-06],
       [2.2278394e-07, 1.3527363e-10, 4.5431364e-07, 9.0210239e-10,
        9.8296434e-01, 2.0209576e-09, 4.2149347e-07, 2.5741781e-05,
        3.7226906e-07, 1.7008429e-02]], dtype=float32)

In [13]:
y_pred = np.argmax(y_pred, axis=1)
y_pred[:5]

array([7, 2, 1, 0, 4])

In [14]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [ ]:
print('Accuracy: ', round(accuracy_score(y_test, y_pred)*100, 2))

Accuracy:  97.84


## Improving using Convolutions

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [ ]:
# for X_train, reshape = (60000, 28,28,1) => appending (60000, 28,28) with 1 like that

X_train = X_train.reshape(X_train.shape[:]+(1,))
X_test = X_test.reshape(X_test.shape[:]+(1,))

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 28, 28, 1), (60000,), (10000, 28, 28, 1), (10000,))

In [ ]:
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

In [ ]:
model = Sequential()
model.add(Conv2D(32, (3,3), activation='relu', input_shape=(X_train.shape[1:])))       
model.add(MaxPooling2D(2, 2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [ ]:
loss = tf.losses.SparseCategoricalCrossentropy()
optimizer = tf.optimizers.Adam(learning_rate=0.001)
metrics = ['accuracy']

In [ ]:
model.compile(loss=loss, optimizer=optimizer, metrics=metrics)

In [ ]:
batch_size = 64
epochs = 10

In [ ]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)  

Epoch 1/10
938/938 - 27s - loss: 0.1876 - accuracy: 0.9443
Epoch 2/10
938/938 - 3s - loss: 0.0599 - accuracy: 0.9818
Epoch 3/10
938/938 - 3s - loss: 0.0395 - accuracy: 0.9882
Epoch 4/10
938/938 - 3s - loss: 0.0272 - accuracy: 0.9916
Epoch 5/10
938/938 - 3s - loss: 0.0194 - accuracy: 0.9936
Epoch 6/10
938/938 - 3s - loss: 0.0133 - accuracy: 0.9960
Epoch 7/10
938/938 - 3s - loss: 0.0113 - accuracy: 0.9963
Epoch 8/10
938/938 - 3s - loss: 0.0079 - accuracy: 0.9977
Epoch 9/10
938/938 - 3s - loss: 0.0064 - accuracy: 0.9982
Epoch 10/10
938/938 - 3s - loss: 0.0061 - accuracy: 0.9980


In [ ]:
model.evaluate(X_test, y_test, batch_size=batch_size, verbose=2) 

157/157 - 1s - loss: 0.0509 - accuracy: 0.9858


[0.05088908225297928, 0.98580002784729]